/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 74
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_Loadthe = 1,
  anon_sym_from = 2,
  anon_sym_DOT = 3,
  anon_sym_Extractthe = 4,
  anon_sym_Summarize = 5,
  anon_sym_Translate = 6,
  anon_sym_to = 7,
  anon_sym_Let = 8,
  anon_sym_be = 9,
  anon_sym_Rewrite = 10,
  anon_sym_Format = 11,
  anon_sym_as = 12,
  anon_sym_using = 13,
  anon_sym_LBRACE_LBRACE = 14,
  anon_sym_prompt_COLON = 15,
  anon_sym_RBRACE_RBRACE = 16,
  anon_sym_it = 17,
  anon_sym_them = 18,
  anon_sym_theresult = 19,
  anon_sym_theoutput = 20,
  anon_sym_this = 21,
  anon_sym_that = 22,
  aux_sym_resource_token1 = 23,
  sym_name = 24,
  anon_sym_DQUOTE = 25,
  aux_sym_string_token1 = 26,
  sym_program = 27,
  sym_sentence = 28,
  sym_load_stmt = 29,
  sym_extract_stmt = 30,
  sym_summarize_stmt = 31,
  sym_translate_stmt = 32,
  sym_bind_stmt = 33,
  sym_rewrite_stmt = 34,
  sym_format_stmt = 35,
  sym_using_prompt = 36,
  sym_prompt_hole = 37,
  sym_resource_from = 38,
  sym_expression = 39,
  sym_input = 40,
  sym_pronoun = 41,
  sym_resource = 42,
  sym_target = 43,
  sym_format_target = 44,
  sym_language = 45,
  sym_string = 46,
  aux_sym_program_repeat1 = 47,
  aux_sym_resource_repeat1 = 48,
  aux_sym_string_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_Loadthe] = "Load the",
  [anon_sym_from] = "from",
  [anon_sym_DOT] = ".",
  [anon_sym_Extractthe] = "Extract the",
  [anon_sym_Summarize] = "Summarize",
  [anon_sym_Translate] = "Translate",
  [anon_sym_to] = "to",
  [anon_sym_Let] = "Let",
  [anon_sym_be] = "be",
  [anon_sym_Rewrite] = "Rewrite",
  [anon_sym_Format] = "Format",
  [anon_sym_as] = "as",
  [anon_sym_using] = "using",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_prompt_COLON] = "prompt:",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_it] = "it",
  [anon_sym_them] = "them",
  [anon_sym_theresult] = "the result",
  [anon_sym_theoutput] = "the output",
  [anon_sym_this] = "this",
  [anon_sym_that] = "that",
  [aux_sym_resource_token1] = "resource_token1",
  [sym_name] = "name",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_program] = "program",
  [sym_sentence] = "sentence",
  [sym_load_stmt] = "load_stmt",
  [sym_extract_stmt] = "extract_stmt",
  [sym_summarize_stmt] = "summarize_stmt",
  [sym_translate_stmt] = "translate_stmt",
  [sym_bind_stmt] = "bind_stmt",
  [sym_rewrite_stmt] = "rewrite_stmt",
  [sym_format_stmt] = "format_stmt",
  [sym_using_prompt] = "using_prompt",
  [sym_prompt_hole] = "prompt_hole",
  [sym_resource_from] = "resource_from",
  [sym_expression] = "expression",
  [sym_input] = "input",
  [sym_pronoun] = "pronoun",
  [sym_resource] = "resource",
  [sym_target] = "target",
  [sym_format_target] = "format_target",
  [sym_language] = "language",
  [sym_string] = "string",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_resource_repeat1] = "resource_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_Loadthe] = anon_sym_Loadthe,
  [anon_sym_from] = anon_sym_from,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_Extractthe] = anon_sym_Extractthe,
  [anon_sym_Summarize] = anon_sym_Summarize,
  [anon_sym_Translate] = anon_sym_Translate,
  [anon_sym_to] = anon_sym_to,
  [anon_sym_Let] = anon_sym_Let,
  [anon_sym_be] = anon_sym_be,
  [anon_sym_Rewrite] = anon_sym_Rewrite,
  [anon_sym_Format] = anon_sym_Format,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_using] = anon_sym_using,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_prompt_COLON] = anon_sym_prompt_COLON,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_it] = anon_sym_it,
  [anon_sym_them] = anon_sym_them,
  [anon_sym_theresult] = anon_sym_theresult,
  [anon_sym_theoutput] = anon_sym_theoutput,
  [anon_sym_this] = anon_sym_this,
  [anon_sym_that] = anon_sym_that,
  [aux_sym_resource_token1] = aux_sym_resource_token1,
  [sym_name] = sym_name,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_program] = sym_program,
  [sym_sentence] = sym_sentence,
  [sym_load_stmt] = sym_load_stmt,
  [sym_extract_stmt] = sym_extract_stmt,
  [sym_summarize_stmt] = sym_summarize_stmt,
  [sym_translate_stmt] = sym_translate_stmt,
  [sym_bind_stmt] = sym_bind_stmt,
  [sym_rewrite_stmt] = sym_rewrite_stmt,
  [sym_format_stmt] = sym_format_stmt,
  [sym_using_prompt] = sym_using_prompt,
  [sym_prompt_hole] = sym_prompt_hole,
  [sym_resource_from] = sym_resource_from,
  [sym_expression] = sym_expression,
  [sym_input] = sym_input,
  [sym_pronoun] = sym_pronoun,
  [sym_resource] = sym_resource,
  [sym_target] = sym_target,
  [sym_format_target] = sym_format_target,
  [sym_language] = sym_language,
  [sym_string] = sym_string,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_resource_repeat1] = aux_sym_resource_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_Loadthe] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Extractthe] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Summarize] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Translate] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_to] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_be] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Rewrite] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Format] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_using] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_prompt_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_it] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_them] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_theresult] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_theoutput] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_this] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_that] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_resource_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence] = {
    .visible = true,
    .named = true,
  },
  [sym_load_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_extract_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_summarize_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_translate_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_bind_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_rewrite_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_format_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_using_prompt] = {
    .visible = true,
    .named = true,
  },
  [sym_prompt_hole] = {
    .visible = true,
    .named = true,
  },
  [sym_resource_from] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_input] = {
    .visible = true,
    .named = true,
  },
  [sym_pronoun] = {
    .visible = true,
    .named = true,
  },
  [sym_resource] = {
    .visible = true,
    .named = true,
  },
  [sym_target] = {
    .visible = true,
    .named = true,
  },
  [sym_format_target] = {
    .visible = true,
    .named = true,
  },
  [sym_language] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_resource_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 22,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 23,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 23,
  [42] = 22,
  [43] = 23,
  [44] = 22,
  [45] = 23,
  [46] = 22,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(88);
      ADVANCE_MAP(
        '"', 156,
        '.', 92,
        'E', 83,
        'F', 47,
        'L', 28,
        'R', 21,
        'S', 78,
        'T', 53,
        'a', 59,
        'b', 22,
        'f', 52,
        'i', 64,
        'p', 58,
        't', 31,
        'u', 60,
        '{', 85,
        '}', 86,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == 'i') ADVANCE(142);
      if (lookahead == 't') ADVANCE(127);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(128);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '.') ADVANCE(92);
      if (lookahead == 'u') ADVANCE(139);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(151);
      if (lookahead != 0) ADVANCE(154);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '.') ADVANCE(92);
      if (lookahead == 'f') ADVANCE(137);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(125);
      if (lookahead != 0) ADVANCE(154);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(4);
      if (lookahead == '.') ADVANCE(92);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(152);
      if (lookahead != 0) ADVANCE(154);
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(5);
      if (lookahead == 't') ADVANCE(135);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(147);
      if (lookahead != 0 &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(6);
      if (lookahead == 'a') ADVANCE(140);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(123);
      if (lookahead != 0 &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(46);
      if (lookahead == 'm') ADVANCE(111);
      END_STATE();
    case 8:
      if (lookahead == ' ') ADVANCE(68);
      END_STATE();
    case 9:
      if (lookahead == ' ') ADVANCE(76);
      END_STATE();
    case 10:
      if (lookahead == '"') ADVANCE(156);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(158);
      if (lookahead != 0) ADVANCE(157);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(107);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(45);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(66);
      if (lookahead == 'e') ADVANCE(7);
      if (lookahead == 'i') ADVANCE(61);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(57);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(67);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(74);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(77);
      END_STATE();
    case 20:
      if (lookahead == 'd') ADVANCE(8);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(82);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(99);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(100);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(89);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(94);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(95);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(93);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(65);
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 30:
      if (lookahead == 'g') ADVANCE(104);
      END_STATE();
    case 31:
      if (lookahead == 'h') ADVANCE(15);
      if (lookahead == 'o') ADVANCE(96);
      END_STATE();
    case 32:
      if (lookahead == 'h') ADVANCE(24);
      END_STATE();
    case 33:
      if (lookahead == 'h') ADVANCE(27);
      END_STATE();
    case 34:
      if (lookahead == 'i') ADVANCE(84);
      END_STATE();
    case 35:
      if (lookahead == 'i') ADVANCE(44);
      END_STATE();
    case 36:
      if (lookahead == 'i') ADVANCE(73);
      END_STATE();
    case 37:
      if (lookahead == 'l') ADVANCE(71);
      END_STATE();
    case 38:
      if (lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 39:
      if (lookahead == 'm') ADVANCE(90);
      END_STATE();
    case 40:
      if (lookahead == 'm') ADVANCE(50);
      END_STATE();
    case 41:
      if (lookahead == 'm') ADVANCE(17);
      END_STATE();
    case 42:
      if (lookahead == 'm') ADVANCE(16);
      END_STATE();
    case 43:
      if (lookahead == 'm') ADVANCE(42);
      END_STATE();
    case 44:
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 45:
      if (lookahead == 'n') ADVANCE(62);
      END_STATE();
    case 46:
      if (lookahead == 'o') ADVANCE(80);
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 47:
      if (lookahead == 'o') ADVANCE(54);
      END_STATE();
    case 48:
      if (lookahead == 'o') ADVANCE(39);
      END_STATE();
    case 49:
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 50:
      if (lookahead == 'p') ADVANCE(69);
      END_STATE();
    case 51:
      if (lookahead == 'p') ADVANCE(81);
      END_STATE();
    case 52:
      if (lookahead == 'r') ADVANCE(48);
      END_STATE();
    case 53:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 54:
      if (lookahead == 'r') ADVANCE(41);
      END_STATE();
    case 55:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 56:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 57:
      if (lookahead == 'r') ADVANCE(34);
      END_STATE();
    case 58:
      if (lookahead == 'r') ADVANCE(49);
      END_STATE();
    case 59:
      if (lookahead == 's') ADVANCE(102);
      END_STATE();
    case 60:
      if (lookahead == 's') ADVANCE(35);
      END_STATE();
    case 61:
      if (lookahead == 's') ADVANCE(117);
      END_STATE();
    case 62:
      if (lookahead == 's') ADVANCE(38);
      END_STATE();
    case 63:
      if (lookahead == 's') ADVANCE(79);
      END_STATE();
    case 64:
      if (lookahead == 't') ADVANCE(109);
      END_STATE();
    case 65:
      if (lookahead == 't') ADVANCE(98);
      END_STATE();
    case 66:
      if (lookahead == 't') ADVANCE(119);
      END_STATE();
    case 67:
      if (lookahead == 't') ADVANCE(101);
      END_STATE();
    case 68:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 69:
      if (lookahead == 't') ADVANCE(11);
      END_STATE();
    case 70:
      if (lookahead == 't') ADVANCE(115);
      END_STATE();
    case 71:
      if (lookahead == 't') ADVANCE(113);
      END_STATE();
    case 72:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 73:
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 74:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 75:
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 76:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 77:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 78:
      if (lookahead == 'u') ADVANCE(43);
      END_STATE();
    case 79:
      if (lookahead == 'u') ADVANCE(37);
      END_STATE();
    case 80:
      if (lookahead == 'u') ADVANCE(72);
      END_STATE();
    case 81:
      if (lookahead == 'u') ADVANCE(70);
      END_STATE();
    case 82:
      if (lookahead == 'w') ADVANCE(55);
      END_STATE();
    case 83:
      if (lookahead == 'x') ADVANCE(75);
      END_STATE();
    case 84:
      if (lookahead == 'z') ADVANCE(25);
      END_STATE();
    case 85:
      if (lookahead == '{') ADVANCE(106);
      END_STATE();
    case 86:
      if (lookahead == '}') ADVANCE(108);
      END_STATE();
    case 87:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(87);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(155);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_Loadthe);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_from);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_Extractthe);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_Summarize);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_Translate);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_to);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_to);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_Let);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_be);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_Rewrite);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_Format);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_as);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_using);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_using);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_prompt_COLON);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_it);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_it);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_them);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_them);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_theresult);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_theresult);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_theoutput);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_theoutput);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_this);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_this);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_that);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_that);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == ' ') ADVANCE(133);
      if (lookahead == 'm') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 'a') ADVANCE(143);
      if (lookahead == 'e') ADVANCE(121);
      if (lookahead == 'i') ADVANCE(138);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 'a') ADVANCE(140);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(123);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 'e') ADVANCE(141);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 'f') ADVANCE(137);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(125);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 'g') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 'h') ADVANCE(122);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 'i') ADVANCE(142);
      if (lookahead == 't') ADVANCE(127);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(128);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(153);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 'i') ADVANCE(132);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 'l') ADVANCE(146);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 'm') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 'n') ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 'o') ADVANCE(148);
      if (lookahead == 'r') ADVANCE(124);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 'o') ADVANCE(131);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 'o') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 'p') ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 'r') ADVANCE(134);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 's') ADVANCE(118);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 's') ADVANCE(129);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 's') ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 's') ADVANCE(149);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 't') ADVANCE(110);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 't') ADVANCE(120);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 't') ADVANCE(136);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 't') ADVANCE(116);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 't') ADVANCE(114);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 't') ADVANCE(135);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(147);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 'u') ADVANCE(144);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 'u') ADVANCE(130);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 'u') ADVANCE(145);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == 'u') ADVANCE(139);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(151);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(152);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(aux_sym_resource_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(154);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(155);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(158);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(157);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 10},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 10},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 10},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 5},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 87},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_Loadthe] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_Extractthe] = ACTIONS(1),
    [anon_sym_Summarize] = ACTIONS(1),
    [anon_sym_Translate] = ACTIONS(1),
    [anon_sym_to] = ACTIONS(1),
    [anon_sym_Let] = ACTIONS(1),
    [anon_sym_be] = ACTIONS(1),
    [anon_sym_Rewrite] = ACTIONS(1),
    [anon_sym_Format] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_using] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_prompt_COLON] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_it] = ACTIONS(1),
    [anon_sym_them] = ACTIONS(1),
    [anon_sym_theresult] = ACTIONS(1),
    [anon_sym_theoutput] = ACTIONS(1),
    [anon_sym_this] = ACTIONS(1),
    [anon_sym_that] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_program] = STATE(69),
    [sym_sentence] = STATE(3),
    [sym_load_stmt] = STATE(10),
    [sym_extract_stmt] = STATE(10),
    [sym_summarize_stmt] = STATE(10),
    [sym_translate_stmt] = STATE(10),
    [sym_bind_stmt] = STATE(10),
    [sym_rewrite_stmt] = STATE(10),
    [sym_format_stmt] = STATE(10),
    [aux_sym_program_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_Loadthe] = ACTIONS(5),
    [anon_sym_Extractthe] = ACTIONS(7),
    [anon_sym_Summarize] = ACTIONS(9),
    [anon_sym_Translate] = ACTIONS(11),
    [anon_sym_Let] = ACTIONS(13),
    [anon_sym_Rewrite] = ACTIONS(15),
    [anon_sym_Format] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_Loadthe,
    ACTIONS(24), 1,
      anon_sym_Extractthe,
    ACTIONS(27), 1,
      anon_sym_Summarize,
    ACTIONS(30), 1,
      anon_sym_Translate,
    ACTIONS(33), 1,
      anon_sym_Let,
    ACTIONS(36), 1,
      anon_sym_Rewrite,
    ACTIONS(39), 1,
      anon_sym_Format,
    STATE(2), 2,
      sym_sentence,
      aux_sym_program_repeat1,
    STATE(10), 7,
      sym_load_stmt,
      sym_extract_stmt,
      sym_summarize_stmt,
      sym_translate_stmt,
      sym_bind_stmt,
      sym_rewrite_stmt,
      sym_format_stmt,
  [38] = 10,
    ACTIONS(5), 1,
      anon_sym_Loadthe,
    ACTIONS(7), 1,
      anon_sym_Extractthe,
    ACTIONS(9), 1,
      anon_sym_Summarize,
    ACTIONS(11), 1,
      anon_sym_Translate,
    ACTIONS(13), 1,
      anon_sym_Let,
    ACTIONS(15), 1,
      anon_sym_Rewrite,
    ACTIONS(17), 1,
      anon_sym_Format,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
    STATE(2), 2,
      sym_sentence,
      aux_sym_program_repeat1,
    STATE(10), 7,
      sym_load_stmt,
      sym_extract_stmt,
      sym_summarize_stmt,
      sym_translate_stmt,
      sym_bind_stmt,
      sym_rewrite_stmt,
      sym_format_stmt,
  [76] = 7,
    ACTIONS(46), 1,
      aux_sym_resource_token1,
    ACTIONS(48), 1,
      sym_name,
    STATE(31), 1,
      aux_sym_resource_repeat1,
    STATE(70), 1,
      sym_pronoun,
    STATE(72), 1,
      sym_resource,
    STATE(71), 2,
      sym_resource_from,
      sym_expression,
    ACTIONS(44), 6,
      anon_sym_it,
      anon_sym_them,
      anon_sym_theresult,
      anon_sym_theoutput,
      anon_sym_this,
      anon_sym_that,
  [104] = 6,
    ACTIONS(50), 1,
      aux_sym_resource_token1,
    ACTIONS(52), 1,
      sym_name,
    STATE(23), 1,
      aux_sym_resource_repeat1,
    STATE(40), 1,
      sym_input,
    STATE(28), 2,
      sym_pronoun,
      sym_resource,
    ACTIONS(44), 6,
      anon_sym_it,
      anon_sym_them,
      anon_sym_theresult,
      anon_sym_theoutput,
      anon_sym_this,
      anon_sym_that,
  [129] = 6,
    ACTIONS(52), 1,
      sym_name,
    ACTIONS(54), 1,
      aux_sym_resource_token1,
    STATE(41), 1,
      aux_sym_resource_repeat1,
    STATE(58), 1,
      sym_input,
    STATE(28), 2,
      sym_pronoun,
      sym_resource,
    ACTIONS(44), 6,
      anon_sym_it,
      anon_sym_them,
      anon_sym_theresult,
      anon_sym_theoutput,
      anon_sym_this,
      anon_sym_that,
  [154] = 6,
    ACTIONS(52), 1,
      sym_name,
    ACTIONS(56), 1,
      aux_sym_resource_token1,
    STATE(43), 1,
      aux_sym_resource_repeat1,
    STATE(67), 1,
      sym_input,
    STATE(28), 2,
      sym_pronoun,
      sym_resource,
    ACTIONS(44), 6,
      anon_sym_it,
      anon_sym_them,
      anon_sym_theresult,
      anon_sym_theoutput,
      anon_sym_this,
      anon_sym_that,
  [179] = 6,
    ACTIONS(52), 1,
      sym_name,
    ACTIONS(58), 1,
      aux_sym_resource_token1,
    STATE(45), 1,
      aux_sym_resource_repeat1,
    STATE(54), 1,
      sym_input,
    STATE(28), 2,
      sym_pronoun,
      sym_resource,
    ACTIONS(44), 6,
      anon_sym_it,
      anon_sym_them,
      anon_sym_theresult,
      anon_sym_theoutput,
      anon_sym_this,
      anon_sym_that,
  [204] = 6,
    ACTIONS(50), 1,
      aux_sym_resource_token1,
    ACTIONS(52), 1,
      sym_name,
    STATE(23), 1,
      aux_sym_resource_repeat1,
    STATE(38), 1,
      sym_input,
    STATE(28), 2,
      sym_pronoun,
      sym_resource,
    ACTIONS(44), 6,
      anon_sym_it,
      anon_sym_them,
      anon_sym_theresult,
      anon_sym_theoutput,
      anon_sym_this,
      anon_sym_that,
  [229] = 1,
    ACTIONS(60), 8,
      ts_builtin_sym_end,
      anon_sym_Loadthe,
      anon_sym_Extractthe,
      anon_sym_Summarize,
      anon_sym_Translate,
      anon_sym_Let,
      anon_sym_Rewrite,
      anon_sym_Format,
  [240] = 1,
    ACTIONS(62), 8,
      ts_builtin_sym_end,
      anon_sym_Loadthe,
      anon_sym_Extractthe,
      anon_sym_Summarize,
      anon_sym_Translate,
      anon_sym_Let,
      anon_sym_Rewrite,
      anon_sym_Format,
  [251] = 1,
    ACTIONS(64), 8,
      ts_builtin_sym_end,
      anon_sym_Loadthe,
      anon_sym_Extractthe,
      anon_sym_Summarize,
      anon_sym_Translate,
      anon_sym_Let,
      anon_sym_Rewrite,
      anon_sym_Format,
  [262] = 1,
    ACTIONS(66), 8,
      ts_builtin_sym_end,
      anon_sym_Loadthe,
      anon_sym_Extractthe,
      anon_sym_Summarize,
      anon_sym_Translate,
      anon_sym_Let,
      anon_sym_Rewrite,
      anon_sym_Format,
  [273] = 1,
    ACTIONS(68), 8,
      ts_builtin_sym_end,
      anon_sym_Loadthe,
      anon_sym_Extractthe,
      anon_sym_Summarize,
      anon_sym_Translate,
      anon_sym_Let,
      anon_sym_Rewrite,
      anon_sym_Format,
  [284] = 1,
    ACTIONS(70), 8,
      ts_builtin_sym_end,
      anon_sym_Loadthe,
      anon_sym_Extractthe,
      anon_sym_Summarize,
      anon_sym_Translate,
      anon_sym_Let,
      anon_sym_Rewrite,
      anon_sym_Format,
  [295] = 1,
    ACTIONS(72), 8,
      ts_builtin_sym_end,
      anon_sym_Loadthe,
      anon_sym_Extractthe,
      anon_sym_Summarize,
      anon_sym_Translate,
      anon_sym_Let,
      anon_sym_Rewrite,
      anon_sym_Format,
  [306] = 1,
    ACTIONS(74), 8,
      ts_builtin_sym_end,
      anon_sym_Loadthe,
      anon_sym_Extractthe,
      anon_sym_Summarize,
      anon_sym_Translate,
      anon_sym_Let,
      anon_sym_Rewrite,
      anon_sym_Format,
  [317] = 1,
    ACTIONS(76), 8,
      ts_builtin_sym_end,
      anon_sym_Loadthe,
      anon_sym_Extractthe,
      anon_sym_Summarize,
      anon_sym_Translate,
      anon_sym_Let,
      anon_sym_Rewrite,
      anon_sym_Format,
  [328] = 1,
    ACTIONS(78), 8,
      ts_builtin_sym_end,
      anon_sym_Loadthe,
      anon_sym_Extractthe,
      anon_sym_Summarize,
      anon_sym_Translate,
      anon_sym_Let,
      anon_sym_Rewrite,
      anon_sym_Format,
  [339] = 1,
    ACTIONS(80), 8,
      ts_builtin_sym_end,
      anon_sym_Loadthe,
      anon_sym_Extractthe,
      anon_sym_Summarize,
      anon_sym_Translate,
      anon_sym_Let,
      anon_sym_Rewrite,
      anon_sym_Format,
  [350] = 1,
    ACTIONS(82), 8,
      ts_builtin_sym_end,
      anon_sym_Loadthe,
      anon_sym_Extractthe,
      anon_sym_Summarize,
      anon_sym_Translate,
      anon_sym_Let,
      anon_sym_Rewrite,
      anon_sym_Format,
  [361] = 3,
    ACTIONS(86), 1,
      aux_sym_resource_token1,
    STATE(22), 1,
      aux_sym_resource_repeat1,
    ACTIONS(84), 2,
      anon_sym_DOT,
      anon_sym_using,
  [372] = 3,
    ACTIONS(91), 1,
      aux_sym_resource_token1,
    STATE(22), 1,
      aux_sym_resource_repeat1,
    ACTIONS(89), 2,
      anon_sym_DOT,
      anon_sym_using,
  [383] = 3,
    ACTIONS(93), 1,
      aux_sym_resource_token1,
    STATE(24), 1,
      aux_sym_resource_repeat1,
    ACTIONS(84), 2,
      anon_sym_from,
      anon_sym_DOT,
  [394] = 3,
    ACTIONS(91), 1,
      aux_sym_resource_token1,
    STATE(22), 1,
      aux_sym_resource_repeat1,
    ACTIONS(96), 2,
      anon_sym_DOT,
      anon_sym_using,
  [405] = 3,
    ACTIONS(100), 1,
      aux_sym_resource_token1,
    STATE(24), 1,
      aux_sym_resource_repeat1,
    ACTIONS(98), 2,
      anon_sym_from,
      anon_sym_DOT,
  [416] = 1,
    ACTIONS(102), 4,
      anon_sym_DOT,
      anon_sym_to,
      anon_sym_as,
      anon_sym_using,
  [423] = 1,
    ACTIONS(104), 4,
      anon_sym_DOT,
      anon_sym_to,
      anon_sym_as,
      anon_sym_using,
  [430] = 3,
    ACTIONS(106), 1,
      aux_sym_resource_token1,
    STATE(26), 1,
      aux_sym_resource_repeat1,
    STATE(53), 1,
      sym_target,
  [440] = 3,
    ACTIONS(108), 1,
      aux_sym_resource_token1,
    STATE(25), 1,
      aux_sym_resource_repeat1,
    STATE(34), 1,
      sym_language,
  [450] = 3,
    ACTIONS(89), 1,
      anon_sym_from,
    ACTIONS(100), 1,
      aux_sym_resource_token1,
    STATE(24), 1,
      aux_sym_resource_repeat1,
  [460] = 3,
    ACTIONS(110), 1,
      aux_sym_resource_token1,
    STATE(35), 1,
      aux_sym_resource_repeat1,
    STATE(61), 1,
      sym_format_target,
  [470] = 3,
    ACTIONS(112), 1,
      anon_sym_DQUOTE,
    ACTIONS(114), 1,
      aux_sym_string_token1,
    STATE(36), 1,
      aux_sym_string_repeat1,
  [480] = 3,
    ACTIONS(116), 1,
      anon_sym_DOT,
    ACTIONS(118), 1,
      anon_sym_using,
    STATE(57), 1,
      sym_using_prompt,
  [490] = 3,
    ACTIONS(120), 1,
      anon_sym_DOT,
    ACTIONS(122), 1,
      aux_sym_resource_token1,
    STATE(46), 1,
      aux_sym_resource_repeat1,
  [500] = 3,
    ACTIONS(124), 1,
      anon_sym_DQUOTE,
    ACTIONS(126), 1,
      aux_sym_string_token1,
    STATE(39), 1,
      aux_sym_string_repeat1,
  [510] = 3,
    ACTIONS(128), 1,
      aux_sym_resource_token1,
    STATE(31), 1,
      aux_sym_resource_repeat1,
    STATE(68), 1,
      sym_resource,
  [520] = 3,
    ACTIONS(118), 1,
      anon_sym_using,
    ACTIONS(130), 1,
      anon_sym_DOT,
    STATE(66), 1,
      sym_using_prompt,
  [530] = 3,
    ACTIONS(132), 1,
      anon_sym_DQUOTE,
    ACTIONS(134), 1,
      aux_sym_string_token1,
    STATE(39), 1,
      aux_sym_string_repeat1,
  [540] = 3,
    ACTIONS(118), 1,
      anon_sym_using,
    ACTIONS(137), 1,
      anon_sym_DOT,
    STATE(59), 1,
      sym_using_prompt,
  [550] = 3,
    ACTIONS(89), 1,
      anon_sym_to,
    ACTIONS(139), 1,
      aux_sym_resource_token1,
    STATE(42), 1,
      aux_sym_resource_repeat1,
  [560] = 3,
    ACTIONS(84), 1,
      anon_sym_to,
    ACTIONS(141), 1,
      aux_sym_resource_token1,
    STATE(42), 1,
      aux_sym_resource_repeat1,
  [570] = 3,
    ACTIONS(89), 1,
      anon_sym_as,
    ACTIONS(144), 1,
      aux_sym_resource_token1,
    STATE(44), 1,
      aux_sym_resource_repeat1,
  [580] = 3,
    ACTIONS(84), 1,
      anon_sym_as,
    ACTIONS(146), 1,
      aux_sym_resource_token1,
    STATE(44), 1,
      aux_sym_resource_repeat1,
  [590] = 3,
    ACTIONS(89), 1,
      anon_sym_DOT,
    ACTIONS(122), 1,
      aux_sym_resource_token1,
    STATE(46), 1,
      aux_sym_resource_repeat1,
  [600] = 3,
    ACTIONS(84), 1,
      anon_sym_DOT,
    ACTIONS(149), 1,
      aux_sym_resource_token1,
    STATE(46), 1,
      aux_sym_resource_repeat1,
  [610] = 2,
    ACTIONS(152), 1,
      anon_sym_DQUOTE,
    STATE(55), 1,
      sym_string,
  [617] = 1,
    ACTIONS(154), 2,
      anon_sym_DOT,
      anon_sym_RBRACE_RBRACE,
  [622] = 2,
    ACTIONS(152), 1,
      anon_sym_DQUOTE,
    STATE(64), 1,
      sym_string,
  [629] = 1,
    ACTIONS(156), 2,
      anon_sym_DOT,
      anon_sym_RBRACE_RBRACE,
  [634] = 2,
    ACTIONS(152), 1,
      anon_sym_DQUOTE,
    STATE(63), 1,
      sym_string,
  [641] = 2,
    ACTIONS(158), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(62), 1,
      sym_prompt_hole,
  [648] = 2,
    ACTIONS(160), 1,
      anon_sym_from,
    ACTIONS(162), 1,
      anon_sym_DOT,
  [655] = 1,
    ACTIONS(164), 1,
      anon_sym_DOT,
  [659] = 1,
    ACTIONS(166), 1,
      anon_sym_DOT,
  [663] = 1,
    ACTIONS(168), 1,
      anon_sym_prompt_COLON,
  [667] = 1,
    ACTIONS(170), 1,
      anon_sym_DOT,
  [671] = 1,
    ACTIONS(172), 1,
      anon_sym_to,
  [675] = 1,
    ACTIONS(174), 1,
      anon_sym_DOT,
  [679] = 1,
    ACTIONS(176), 1,
      anon_sym_be,
  [683] = 1,
    ACTIONS(178), 1,
      anon_sym_DOT,
  [687] = 1,
    ACTIONS(180), 1,
      anon_sym_DOT,
  [691] = 1,
    ACTIONS(182), 1,
      anon_sym_RBRACE_RBRACE,
  [695] = 1,
    ACTIONS(184), 1,
      anon_sym_DOT,
  [699] = 1,
    ACTIONS(186), 1,
      anon_sym_DOT,
  [703] = 1,
    ACTIONS(188), 1,
      anon_sym_DOT,
  [707] = 1,
    ACTIONS(190), 1,
      anon_sym_as,
  [711] = 1,
    ACTIONS(192), 1,
      anon_sym_from,
  [715] = 1,
    ACTIONS(194), 1,
      ts_builtin_sym_end,
  [719] = 1,
    ACTIONS(196), 1,
      anon_sym_DOT,
  [723] = 1,
    ACTIONS(198), 1,
      anon_sym_DOT,
  [727] = 1,
    ACTIONS(200), 1,
      anon_sym_from,
  [731] = 1,
    ACTIONS(202), 1,
      sym_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 76,
  [SMALL_STATE(5)] = 104,
  [SMALL_STATE(6)] = 129,
  [SMALL_STATE(7)] = 154,
  [SMALL_STATE(8)] = 179,
  [SMALL_STATE(9)] = 204,
  [SMALL_STATE(10)] = 229,
  [SMALL_STATE(11)] = 240,
  [SMALL_STATE(12)] = 251,
  [SMALL_STATE(13)] = 262,
  [SMALL_STATE(14)] = 273,
  [SMALL_STATE(15)] = 284,
  [SMALL_STATE(16)] = 295,
  [SMALL_STATE(17)] = 306,
  [SMALL_STATE(18)] = 317,
  [SMALL_STATE(19)] = 328,
  [SMALL_STATE(20)] = 339,
  [SMALL_STATE(21)] = 350,
  [SMALL_STATE(22)] = 361,
  [SMALL_STATE(23)] = 372,
  [SMALL_STATE(24)] = 383,
  [SMALL_STATE(25)] = 394,
  [SMALL_STATE(26)] = 405,
  [SMALL_STATE(27)] = 416,
  [SMALL_STATE(28)] = 423,
  [SMALL_STATE(29)] = 430,
  [SMALL_STATE(30)] = 440,
  [SMALL_STATE(31)] = 450,
  [SMALL_STATE(32)] = 460,
  [SMALL_STATE(33)] = 470,
  [SMALL_STATE(34)] = 480,
  [SMALL_STATE(35)] = 490,
  [SMALL_STATE(36)] = 500,
  [SMALL_STATE(37)] = 510,
  [SMALL_STATE(38)] = 520,
  [SMALL_STATE(39)] = 530,
  [SMALL_STATE(40)] = 540,
  [SMALL_STATE(41)] = 550,
  [SMALL_STATE(42)] = 560,
  [SMALL_STATE(43)] = 570,
  [SMALL_STATE(44)] = 580,
  [SMALL_STATE(45)] = 590,
  [SMALL_STATE(46)] = 600,
  [SMALL_STATE(47)] = 610,
  [SMALL_STATE(48)] = 617,
  [SMALL_STATE(49)] = 622,
  [SMALL_STATE(50)] = 629,
  [SMALL_STATE(51)] = 634,
  [SMALL_STATE(52)] = 641,
  [SMALL_STATE(53)] = 648,
  [SMALL_STATE(54)] = 655,
  [SMALL_STATE(55)] = 659,
  [SMALL_STATE(56)] = 663,
  [SMALL_STATE(57)] = 667,
  [SMALL_STATE(58)] = 671,
  [SMALL_STATE(59)] = 675,
  [SMALL_STATE(60)] = 679,
  [SMALL_STATE(61)] = 683,
  [SMALL_STATE(62)] = 687,
  [SMALL_STATE(63)] = 691,
  [SMALL_STATE(64)] = 695,
  [SMALL_STATE(65)] = 699,
  [SMALL_STATE(66)] = 703,
  [SMALL_STATE(67)] = 707,
  [SMALL_STATE(68)] = 711,
  [SMALL_STATE(69)] = 715,
  [SMALL_STATE(70)] = 719,
  [SMALL_STATE(71)] = 723,
  [SMALL_STATE(72)] = 727,
  [SMALL_STATE(73)] = 731,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extract_stmt, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_summarize_stmt, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rewrite_stmt, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_summarize_stmt, 4, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rewrite_stmt, 4, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_load_stmt, 5, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extract_stmt, 5, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_translate_stmt, 5, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bind_stmt, 5, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_stmt, 5, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_translate_stmt, 6, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_resource_repeat1, 2, 0, 0),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_resource_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_resource, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_resource_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_language, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_target, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pronoun, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format_target, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [141] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_resource_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [146] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_resource_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_resource_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_using_prompt, 2, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resource_from, 3, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prompt_hole, 4, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [194] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_limelightx(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "limelightx",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
